language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - git submodule update --remote

install:
  - pip install --upgrade -r requirements.txt

script:
  - py.test --cov=./
  - python -m doctest -v *.py

after_success:
  - flake8 --max-line-length 100 --ignore=E121,E123,E126,E221,E222,E225,E226,E242,E701,E702,E704,E731,W503 .

notifications:
  email: false
